version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - app-network
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
